const API_URI = {
  BASE: '/api',
  LOGIN: '',
  SINGUP: '',
  KAKAO_LOGIN: '/login/oauth',
  VALID_CHECK: '/member/check/nickname',
  USER_INFO: '/member/profile-info',
  PLACE_INFO: '/place/search',
  SUBMIT_DATECOURSE: '/course/add',
  STATION_AUTOCOMPLETE: '/subway',
  RECOMMEND: '/course/recommendation',
  COURSE_DETAIL: '/course/details',
  HOT_ARTICLE: '/post/recommend',
  SEARCH_ARTICLE: '/post',
  ARTICLE_DETAIL: '/post-content',
  MY_FAV_COURSE: '/member/myfavcourse',
  MY_FAV_COURSE_DETAIL: '/course/details',
  GENERATE_LINK: '/couple/generate-link',
  PROFILE_INFO: '/member/profile',
  MODIFY_PROFILE_COUPLE: 'member/update/couple-profile',
  MODIFY_PROFILE: 'member/update/profile',
}
export default API_URI
